<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends EntityRepository
{
    /**
     * Find a user's current ongoing basket.  A user may have many baskets, but only
     * one is expected to be in the ongoing state.
     */
    public function findByUserOngoing($userId)
    {
        $dql = "SELECT b
                  FROM NiftyThrifty\ShopBundle\Entity\Basket b
                 WHERE b.userId = :userId
                   AND b.basketStatus = :basketStatus";
        $params = array('userId'       => $userId, 
                        'basketStatus' => \NiftyThrifty\ShopBundle\Entity\Basket::ONGOING);
                        
        try {
            $basket = $this->runSingleResultQuery($dql, $params);
        } catch (NoResultException $e) {
            $basket = null;
        }
        
        return $basket;
    }
}
