<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends EntityRepository
{
    /**
     * Find a coupon by the text entity.  This is case insensitive and should only return
     * if it's an unexpired coupon.
     */
    public function findUnexpiredByCouponCode($code='')
    {
        $code = trim($code);
        $dql  = 'SELECT c
                   FROM NiftyThrifty\ShopBundle\Entity\Coupon c
                  WHERE UPPER(c.couponCode) = UPPER(:code)
                    AND c.couponDateEnd > CURRENT_TIMESTAMP()';
        $params = array('code' => $code);
        
        return $this->runSingleResultQuery($dql, $params);
    }

    public function findUnexpiredByCouponId($couponId)
    {
        $dql = 'SELECT c
                  FROM NiftyThrifty\ShopBundle\Entity\Coupon c
                 WHERE c.couponId = :couponId
                   AND c.couponDateEnd > CURRENT_TIMESTAMP()';
        $params = array('couponId' => $couponId);

        return $this->runSingleResultQuery($dql, $params);
    }
}
