<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * NiftyThrifty\ShopBundle\Entity\Invoice
 * Note: there is no validation on this class because it is not generated by any user input.  It is 
 *  built from Orders and other things previously saved, all of which themselves have validation.
 *
 * @ORM\Table(name="invoice")
 * @ORM\Entity
 */
class Invoice
{
    /**
     * @var integer $invoiceId
     *
     * @ORM\Column(name="invoice_id", type="bigint", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $invoiceId;

    /**
     * @var string $invoiceNum
     *
     * @ORM\Column(name="invoice_num", type="string", length=100, nullable=false)
     */
    private $invoiceNum;

    /**
     * @var integer $orderId
     *
     * @ORM\Column(name="order_id", type="bigint", nullable=false)
     */
    private $orderId;

    /**
     * @var integer $basketId
     *
     * @ORM\Column(name="basket_id", type="bigint", nullable=false)
     */
    private $basketId;

    /**
     * @var string $invoiceStatus
     *
     * @ORM\Column(name="invoice_status", type="string", nullable=false)
     */
    private $invoiceStatus;

    /**
     * @var \DateTime $invoiceDate
     *
     * @ORM\Column(name="invoice_date", type="datetime", nullable=true)
     */
    private $invoiceDate;

    /**
     * @var integer $userId
     *
     * @ORM\Column(name="user_id", type="bigint", nullable=false)
     */
    private $userId;

    /**
     * @var string $invoiceUserFirstName
     *
     * @ORM\Column(name="invoice_user_first_name", type="string", length=100, nullable=false)
     */
    private $invoiceUserFirstName;

    /**
     * @var string $invoiceUserLastName
     *
     * @ORM\Column(name="invoice_user_last_name", type="string", length=100, nullable=false)
     */
    private $invoiceUserLastName;

    /**
     * @var string $invoiceUserEmail
     *
     * @ORM\Column(name="invoice_user_email", type="string", length=100, nullable=false)
     */
    private $invoiceUserEmail;

    /**
     * @var float $invoiceAmount
     *
     * @ORM\Column(name="invoice_amount", type="float", nullable=false)
     */
    private $invoiceAmount;

    /**
     * @var float $invoiceAmountCoupon
     *
     * @ORM\Column(name="invoice_amount_coupon", type="float", nullable=false)
     */
    private $invoiceAmountCoupon;

    /**
     * @var float $invoiceAmountVat
     *
     * @ORM\Column(name="invoice_amount_vat", type="float", nullable=false)
     */
    private $invoiceAmountVat;

    /**
     * @var float $invoiceAmountShipping
     *
     * @ORM\Column(name="invoice_amount_shipping", type="float", nullable=false)
     */
    private $invoiceAmountShipping;

    /**
     * @var float $invoiceAmountCredits
     *
     * @ORM\Column(name="invoice_amount_credits", type="float", nullable=false)
     */
    private $invoiceAmountCredits;

    /**
     * @var float $invoiceAmountTotal
     *
     * @ORM\Column(name="invoice_amount_total", type="float", nullable=false)
     */
    private $invoiceAmountTotal;

    /**
     * @var string $invoiceProducts
     *
     * @ORM\Column(name="invoice_products", type="text", nullable=false)
     */
    private $invoiceProducts;

    /**
     * @var string $invoiceShippingMethod
     *
     * @ORM\Column(name="invoice_shipping_method", type="string", nullable=true)
     */
    private $invoiceShippingMethod;

    /**
     * @var string $invoiceShippingAddressFirstName
     *
     * @ORM\Column(name="invoice_shipping_address_first_name", type="string", length=64, nullable=false)
     */
    private $invoiceShippingAddressFirstName;

    /**
     * @var string $invoiceShippingAddressLastName
     *
     * @ORM\Column(name="invoice_shipping_address_last_name", type="string", length=64, nullable=false)
     */
    private $invoiceShippingAddressLastName;

    /**
     * @var string $invoiceShippingAddressStreet
     *
     * @ORM\Column(name="invoice_shipping_address_street", type="string", length=255, nullable=false)
     */
    private $invoiceShippingAddressStreet;

    /**
     * @var string $invoiceShippingAddressCity
     *
     * @ORM\Column(name="invoice_shipping_address_city", type="string", length=64, nullable=false)
     */
    private $invoiceShippingAddressCity;

    /**
     * @var string $invoiceShippingAddressState
     *
     * @ORM\Column(name="invoice_shipping_address_state", type="string", length=64, nullable=false)
     */
    private $invoiceShippingAddressState;

    /**
     * @var string $invoiceShippingAddressZipcode
     *
     * @ORM\Column(name="invoice_shipping_address_zipcode", type="string", length=20, nullable=false)
     */
    private $invoiceShippingAddressZipcode;

    /**
     * @var string $invoiceShippingAddressCountry
     *
     * @ORM\Column(name="invoice_shipping_address_country", type="string", length=64, nullable=false)
     */
    private $invoiceShippingAddressCountry;

    /**
     * @var string $invoiceShippingStatus
     *
     * @ORM\Column(name="invoice_shipping_status", type="string", nullable=true)
     */
    private $invoiceShippingStatus;

    /**
     * @var string $invoiceShippingTrackingUrl
     *
     * @ORM\Column(name="invoice_shipping_tracking_url", type="string", length=1024, nullable=true)
     */
    private $invoiceShippingTrackingUrl;

    /**
     * @var string $invoiceBillingAddressFirstName
     *
     * @ORM\Column(name="invoice_billing_address_first_name", type="string", length=64, nullable=false)
     */
    private $invoiceBillingAddressFirstName;

    /**
     * @var string $invoiceBillingAddressLastName
     *
     * @ORM\Column(name="invoice_billing_address_last_name", type="string", length=64, nullable=false)
     */
    private $invoiceBillingAddressLastName;

    /**
     * @var string $invoiceBillingAddressStreet
     *
     * @ORM\Column(name="invoice_billing_address_street", type="string", length=255, nullable=false)
     */
    private $invoiceBillingAddressStreet;

    /**
     * @var string $invoiceBillingAddressCity
     *
     * @ORM\Column(name="invoice_billing_address_city", type="string", length=64, nullable=false)
     */
    private $invoiceBillingAddressCity;

    /**
     * @var string $invoiceBillingAddressState
     *
     * @ORM\Column(name="invoice_billing_address_state", type="string", length=64, nullable=false)
     */
    private $invoiceBillingAddressState;

    /**
     * @var string $invoiceBillingAddressZipcode
     *
     * @ORM\Column(name="invoice_billing_address_zipcode", type="string", length=20, nullable=false)
     */
    private $invoiceBillingAddressZipcode;

    /**
     * @var string $invoiceBillingAddressCountry
     *
     * @ORM\Column(name="invoice_billing_address_country", type="string", length=64, nullable=false)
     */
    private $invoiceBillingAddressCountry;

    /**
     * @var string $invoiceUserIpAddress
     *
     * @ORM\Column(name="invoice_user_ip_address", type="string", length=255, nullable=false)
     */
    private $invoiceUserIpAddress;

    /**
     * @var integer $couponId
     *
     * @ORM\Column(name="coupon_id", type="bigint", nullable=true)
     */
    private $couponId;
    
    const SHIPPING_STATUS_PROCESSING    = 'processing';
    const SHIPPING_STATUS_EXPEDITED     = 'expedited';
    const SHIPPING_STATUS_TRACKING      = 'track shipment';
    const SHIPPING_STATUS_SHIPPWED      = 'shipped';

    /**
     * Given an order object, populate the same fields in this invoice object with those same
     * values.  This will take any fields named exactly the same (like coupon_id) and set them.
     * It will also replace the word "invoice" with "order" when checking the order object, so
     * "invoiceStatus" will be set to the value of "orderStatus".  Any fields without a getter
     * method (ie: getOrderNum) are ignored.  The PK field (invoiceId) is also explicitly ignored
     * since auto_increment will give us a unique ID on persist.
     *
     * @param   $order      an Order object from the Nifty Bundle
     * @return  Invoice
     */
    public function setFromOrder($order)
    {
        $reference = new \ReflectionClass('\NiftyThrifty\ShopBundle\Entity\Invoice');
        $properties = $reference->getProperties(\ReflectionProperty::IS_PRIVATE);

        /**
         * Go through each property... if a getter exists in the Order class, use it
         * to set the variable in this class with whatever that getter has in it.
         */
        $ignoreFields = array('invoiceId');
        foreach ($properties as $property) {
            $varName = $property->name;

            if (in_array($varName, $ignoreFields)) continue;

            $getter = 'get' . str_replace('invoice', 'Order', $varName);
            if (method_exists($order, $getter)) {
                $this->$varName = $order->$getter();
            }
        }
        $this->setOrder($order);
        $this->invoiceShippingStatus 
                = $order->getOrderShippingMethod() == \NiftyThrifty\ShopBundle\Service\ShippingCostService::EXPRESS_SHIPPING 
                ? self::SHIPPING_STATUS_EXPEDITED 
                : self::SHIPPING_STATUS_PROCESSING;
        $this->invoiceDate = new \DateTime();
        return $this;
    }

    /**
     * Get invoiceId
     *
     * @return integer 
     */
    public function getInvoiceId()
    {
        return $this->invoiceId;
    }

    /**
     * Set invoiceNum
     *
     * @param string $invoiceNum
     * @return Invoice
     */
    public function setInvoiceNum($invoiceNum)
    {
        $this->invoiceNum = $invoiceNum;
    
        return $this;
    }

    /**
     * Get invoiceNum
     *
     * @return string 
     */
    public function getInvoiceNum()
    {
        return $this->invoiceNum;
    }

    /**
     * Set orderId
     *
     * @param integer $orderId
     * @return Invoice
     */
    public function setOrderId($orderId)
    {
        $this->orderId = $orderId;
    
        return $this;
    }

    /**
     * Get orderId
     *
     * @return integer 
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Set basketId
     *
     * @param integer $basketId
     * @return Invoice
     */
    public function setBasketId($basketId)
    {
        $this->basketId = $basketId;
    
        return $this;
    }

    /**
     * Get basketId
     *
     * @return integer 
     */
    public function getBasketId()
    {
        return $this->basketId;
    }

    /**
     * Set invoiceStatus
     *
     * @param string $invoiceStatus
     * @return Invoice
     */
    public function setInvoiceStatus($invoiceStatus)
    {
        $this->invoiceStatus = $invoiceStatus;
    
        return $this;
    }

    /**
     * Get invoiceStatus
     *
     * @return string 
     */
    public function getInvoiceStatus()
    {
        return $this->invoiceStatus;
    }

    /**
     * Set invoiceDate
     *
     * @param \DateTime $invoiceDate
     * @return Invoice
     */
    public function setInvoiceDate($invoiceDate)
    {
        $this->invoiceDate = $invoiceDate;
    
        return $this;
    }

    /**
     * Get invoiceDate
     *
     * @return \DateTime 
     */
    public function getInvoiceDate()
    {
        return $this->invoiceDate;
    }

    /**
     * Set userId
     *
     * @param integer $userId
     * @return Invoice
     */
    public function setUserId($userId)
    {
        $this->userId = $userId;
    
        return $this;
    }

    /**
     * Get userId
     *
     * @return integer 
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Set invoiceUserFirstName
     *
     * @param string $invoiceUserFirstName
     * @return Invoice
     */
    public function setInvoiceUserFirstName($invoiceUserFirstName)
    {
        $this->invoiceUserFirstName = $invoiceUserFirstName;
    
        return $this;
    }

    /**
     * Get invoiceUserFirstName
     *
     * @return string 
     */
    public function getInvoiceUserFirstName()
    {
        return $this->invoiceUserFirstName;
    }

    /**
     * Set invoiceUserLastName
     *
     * @param string $invoiceUserLastName
     * @return Invoice
     */
    public function setInvoiceUserLastName($invoiceUserLastName)
    {
        $this->invoiceUserLastName = $invoiceUserLastName;
    
        return $this;
    }

    /**
     * Get invoiceUserLastName
     *
     * @return string 
     */
    public function getInvoiceUserLastName()
    {
        return $this->invoiceUserLastName;
    }

    /**
     * Set invoiceUserEmail
     *
     * @param string $invoiceUserEmail
     * @return Invoice
     */
    public function setInvoiceUserEmail($invoiceUserEmail)
    {
        $this->invoiceUserEmail = $invoiceUserEmail;
    
        return $this;
    }

    /**
     * Get invoiceUserEmail
     *
     * @return string 
     */
    public function getInvoiceUserEmail()
    {
        return $this->invoiceUserEmail;
    }

    /**
     * Set invoiceAmount
     *
     * @param float $invoiceAmount
     * @return Invoice
     */
    public function setInvoiceAmount($invoiceAmount)
    {
        $this->invoiceAmount = $invoiceAmount;
    
        return $this;
    }

    /**
     * Get invoiceAmount
     *
     * @return float 
     */
    public function getInvoiceAmount()
    {
        return $this->invoiceAmount;
    }

    /**
     * Set invoiceAmountCoupon
     *
     * @param float $invoiceAmountCoupon
     * @return Invoice
     */
    public function setInvoiceAmountCoupon($invoiceAmountCoupon)
    {
        $this->invoiceAmountCoupon = $invoiceAmountCoupon;
    
        return $this;
    }

    /**
     * Get invoiceAmountCoupon
     *
     * @return float 
     */
    public function getInvoiceAmountCoupon()
    {
        return $this->invoiceAmountCoupon;
    }

    /**
     * Set invoiceAmountVat
     *
     * @param float $invoiceAmountVat
     * @return Invoice
     */
    public function setInvoiceAmountVat($invoiceAmountVat)
    {
        $this->invoiceAmountVat = $invoiceAmountVat;
    
        return $this;
    }

    /**
     * Get invoiceAmountVat
     *
     * @return float 
     */
    public function getInvoiceAmountVat()
    {
        return $this->invoiceAmountVat;
    }

    /**
     * Set invoiceAmountShipping
     *
     * @param float $invoiceAmountShipping
     * @return Invoice
     */
    public function setInvoiceAmountShipping($invoiceAmountShipping)
    {
        $this->invoiceAmountShipping = $invoiceAmountShipping;
    
        return $this;
    }

    /**
     * Get invoiceAmountShipping
     *
     * @return float 
     */
    public function getInvoiceAmountShipping()
    {
        return $this->invoiceAmountShipping;
    }

    /**
     * Set invoiceAmountCredits
     *
     * @param float $invoiceAmountCredits
     * @return Invoice
     */
    public function setInvoiceAmountCredits($invoiceAmountCredits)
    {
        $this->invoiceAmountCredits = $invoiceAmountCredits;
    
        return $this;
    }

    /**
     * Get invoiceAmountCredits
     *
     * @return float 
     */
    public function getInvoiceAmountCredits()
    {
        return $this->invoiceAmountCredits;
    }

    /**
     * Set invoiceAmountTotal
     *
     * @param float $invoiceAmountTotal
     * @return Invoice
     */
    public function setInvoiceAmountTotal($invoiceAmountTotal)
    {
        $this->invoiceAmountTotal = $invoiceAmountTotal;
    
        return $this;
    }

    /**
     * Get invoiceAmountTotal
     *
     * @return float 
     */
    public function getInvoiceAmountTotal()
    {
        return $this->invoiceAmountTotal;
    }

    /**
     * Set invoiceProducts
     *
     * @param string $invoiceProducts
     * @return Invoice
     */
    public function setInvoiceProducts($invoiceProducts)
    {
        $this->invoiceProducts = $invoiceProducts;
    
        return $this;
    }

    /**
     * Get invoiceProducts
     *
     * @return string 
     */
    public function getInvoiceProducts()
    {
        return $this->invoiceProducts;
    }

    /**
     * Set invoiceShippingMethod
     *
     * @param string $invoiceShippingMethod
     * @return Invoice
     */
    public function setInvoiceShippingMethod($invoiceShippingMethod)
    {
        $this->invoiceShippingMethod = $invoiceShippingMethod;
    
        return $this;
    }

    /**
     * Get invoiceShippingMethod
     *
     * @return string 
     */
    public function getInvoiceShippingMethod()
    {
        return $this->invoiceShippingMethod;
    }

    /**
     * Set invoiceShippingAddressFirstName
     *
     * @param string $invoiceShippingAddressFirstName
     * @return Invoice
     */
    public function setInvoiceShippingAddressFirstName($invoiceShippingAddressFirstName)
    {
        $this->invoiceShippingAddressFirstName = $invoiceShippingAddressFirstName;
    
        return $this;
    }

    /**
     * Get invoiceShippingAddressFirstName
     *
     * @return string 
     */
    public function getInvoiceShippingAddressFirstName()
    {
        return $this->invoiceShippingAddressFirstName;
    }

    /**
     * Set invoiceShippingAddressLastName
     *
     * @param string $invoiceShippingAddressLastName
     * @return Invoice
     */
    public function setInvoiceShippingAddressLastName($invoiceShippingAddressLastName)
    {
        $this->invoiceShippingAddressLastName = $invoiceShippingAddressLastName;
    
        return $this;
    }

    /**
     * Get invoiceShippingAddressLastName
     *
     * @return string 
     */
    public function getInvoiceShippingAddressLastName()
    {
        return $this->invoiceShippingAddressLastName;
    }

    /**
     * Set invoiceShippingAddressStreet
     *
     * @param string $invoiceShippingAddressStreet
     * @return Invoice
     */
    public function setInvoiceShippingAddressStreet($invoiceShippingAddressStreet)
    {
        $this->invoiceShippingAddressStreet = $invoiceShippingAddressStreet;
    
        return $this;
    }

    /**
     * Get invoiceShippingAddressStreet
     *
     * @return string 
     */
    public function getInvoiceShippingAddressStreet()
    {
        return $this->invoiceShippingAddressStreet;
    }

    /**
     * Set invoiceShippingAddressCity
     *
     * @param string $invoiceShippingAddressCity
     * @return Invoice
     */
    public function setInvoiceShippingAddressCity($invoiceShippingAddressCity)
    {
        $this->invoiceShippingAddressCity = $invoiceShippingAddressCity;
    
        return $this;
    }

    /**
     * Get invoiceShippingAddressCity
     *
     * @return string 
     */
    public function getInvoiceShippingAddressCity()
    {
        return $this->invoiceShippingAddressCity;
    }

    /**
     * Set invoiceShippingAddressState
     *
     * @param string $invoiceShippingAddressState
     * @return Invoice
     */
    public function setInvoiceShippingAddressState($invoiceShippingAddressState)
    {
        $this->invoiceShippingAddressState = $invoiceShippingAddressState;
    
        return $this;
    }

    /**
     * Get invoiceShippingAddressState
     *
     * @return string 
     */
    public function getInvoiceShippingAddressState()
    {
        return $this->invoiceShippingAddressState;
    }

    /**
     * Set invoiceShippingAddressZipcode
     *
     * @param string $invoiceShippingAddressZipcode
     * @return Invoice
     */
    public function setInvoiceShippingAddressZipcode($invoiceShippingAddressZipcode)
    {
        $this->invoiceShippingAddressZipcode = $invoiceShippingAddressZipcode;
    
        return $this;
    }

    /**
     * Get invoiceShippingAddressZipcode
     *
     * @return string 
     */
    public function getInvoiceShippingAddressZipcode()
    {
        return $this->invoiceShippingAddressZipcode;
    }

    /**
     * Set invoiceShippingAddressCountry
     *
     * @param string $invoiceShippingAddressCountry
     * @return Invoice
     */
    public function setInvoiceShippingAddressCountry($invoiceShippingAddressCountry)
    {
        $this->invoiceShippingAddressCountry = $invoiceShippingAddressCountry;
    
        return $this;
    }

    /**
     * Get invoiceShippingAddressCountry
     *
     * @return string 
     */
    public function getInvoiceShippingAddressCountry()
    {
        return $this->invoiceShippingAddressCountry;
    }

    /**
     * Set invoiceShippingStatus
     *
     * @param string $invoiceShippingStatus
     * @return Invoice
     */
    public function setInvoiceShippingStatus($invoiceShippingStatus)
    {
        $this->invoiceShippingStatus = $invoiceShippingStatus;
    
        return $this;
    }

    /**
     * Get invoiceShippingStatus
     *
     * @return string 
     */
    public function getInvoiceShippingStatus()
    {
        return $this->invoiceShippingStatus;
    }

    /**
     * Set invoiceShippingTrackingUrl
     *
     * @param string $invoiceShippingTrackingUrl
     * @return Invoice
     */
    public function setInvoiceShippingTrackingUrl($invoiceShippingTrackingUrl)
    {
        $this->invoiceShippingTrackingUrl = $invoiceShippingTrackingUrl;
    
        return $this;
    }

    /**
     * Get invoiceShippingTrackingUrl
     *
     * @return string 
     */
    public function getInvoiceShippingTrackingUrl()
    {
        return $this->invoiceShippingTrackingUrl;
    }

    /**
     * Set invoiceBillingAddressFirstName
     *
     * @param string $invoiceBillingAddressFirstName
     * @return Invoice
     */
    public function setInvoiceBillingAddressFirstName($invoiceBillingAddressFirstName)
    {
        $this->invoiceBillingAddressFirstName = $invoiceBillingAddressFirstName;
    
        return $this;
    }

    /**
     * Get invoiceBillingAddressFirstName
     *
     * @return string 
     */
    public function getInvoiceBillingAddressFirstName()
    {
        return $this->invoiceBillingAddressFirstName;
    }

    /**
     * Set invoiceBillingAddressLastName
     *
     * @param string $invoiceBillingAddressLastName
     * @return Invoice
     */
    public function setInvoiceBillingAddressLastName($invoiceBillingAddressLastName)
    {
        $this->invoiceBillingAddressLastName = $invoiceBillingAddressLastName;
    
        return $this;
    }

    /**
     * Get invoiceBillingAddressLastName
     *
     * @return string 
     */
    public function getInvoiceBillingAddressLastName()
    {
        return $this->invoiceBillingAddressLastName;
    }

    /**
     * Set invoiceBillingAddressStreet
     *
     * @param string $invoiceBillingAddressStreet
     * @return Invoice
     */
    public function setInvoiceBillingAddressStreet($invoiceBillingAddressStreet)
    {
        $this->invoiceBillingAddressStreet = $invoiceBillingAddressStreet;
    
        return $this;
    }

    /**
     * Get invoiceBillingAddressStreet
     *
     * @return string 
     */
    public function getInvoiceBillingAddressStreet()
    {
        return $this->invoiceBillingAddressStreet;
    }

    /**
     * Set invoiceBillingAddressCity
     *
     * @param string $invoiceBillingAddressCity
     * @return Invoice
     */
    public function setInvoiceBillingAddressCity($invoiceBillingAddressCity)
    {
        $this->invoiceBillingAddressCity = $invoiceBillingAddressCity;
    
        return $this;
    }

    /**
     * Get invoiceBillingAddressCity
     *
     * @return string 
     */
    public function getInvoiceBillingAddressCity()
    {
        return $this->invoiceBillingAddressCity;
    }

    /**
     * Set invoiceBillingAddressState
     *
     * @param string $invoiceBillingAddressState
     * @return Invoice
     */
    public function setInvoiceBillingAddressState($invoiceBillingAddressState)
    {
        $this->invoiceBillingAddressState = $invoiceBillingAddressState;
    
        return $this;
    }

    /**
     * Get invoiceBillingAddressState
     *
     * @return string 
     */
    public function getInvoiceBillingAddressState()
    {
        return $this->invoiceBillingAddressState;
    }

    /**
     * Set invoiceBillingAddressZipcode
     *
     * @param string $invoiceBillingAddressZipcode
     * @return Invoice
     */
    public function setInvoiceBillingAddressZipcode($invoiceBillingAddressZipcode)
    {
        $this->invoiceBillingAddressZipcode = $invoiceBillingAddressZipcode;
    
        return $this;
    }

    /**
     * Get invoiceBillingAddressZipcode
     *
     * @return string 
     */
    public function getInvoiceBillingAddressZipcode()
    {
        return $this->invoiceBillingAddressZipcode;
    }

    /**
     * Set invoiceBillingAddressCountry
     *
     * @param string $invoiceBillingAddressCountry
     * @return Invoice
     */
    public function setInvoiceBillingAddressCountry($invoiceBillingAddressCountry)
    {
        $this->invoiceBillingAddressCountry = $invoiceBillingAddressCountry;
    
        return $this;
    }

    /**
     * Get invoiceBillingAddressCountry
     *
     * @return string 
     */
    public function getInvoiceBillingAddressCountry()
    {
        return $this->invoiceBillingAddressCountry;
    }

    /**
     * Set invoiceUserIpAddress
     *
     * @param string $invoiceUserIpAddress
     * @return Invoice
     */
    public function setInvoiceUserIpAddress($invoiceUserIpAddress)
    {
        $this->invoiceUserIpAddress = $invoiceUserIpAddress;
    
        return $this;
    }

    /**
     * Get invoiceUserIpAddress
     *
     * @return string 
     */
    public function getInvoiceUserIpAddress()
    {
        return $this->invoiceUserIpAddress;
    }

    /**
     * Set couponId
     *
     * @param integer $couponId
     * @return Invoice
     */
    public function setCouponId($couponId)
    {
        $this->couponId = $couponId;
    
        return $this;
    }

    /**
     * Get couponId
     *
     * @return integer 
     */
    public function getCouponId()
    {
        return $this->couponId;
    }
    /**
     * @var \NiftyThrifty\ShopBundle\Entity\Order
     */
    private $order;

    /**
     * @var \NiftyThrifty\ShopBundle\Entity\Basket
     */
    private $basket;

    /**
     * @var \NiftyThrifty\ShopBundle\Entity\User
     */
    private $user;


    /**
     * Set order
     *
     * @param \NiftyThrifty\ShopBundle\Entity\Order $order
     * @return Invoice
     */
    public function setOrder(\NiftyThrifty\ShopBundle\Entity\Order $order = null)
    {
        $this->order = $order;
    
        return $this;
    }

    /**
     * Get order
     *
     * @return \NiftyThrifty\ShopBundle\Entity\Order 
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Set basket
     *
     * @param \NiftyThrifty\ShopBundle\Entity\Basket $basket
     * @return Invoice
     */
    public function setBasket(\NiftyThrifty\ShopBundle\Entity\Basket $basket = null)
    {
        $this->basket = $basket;
    
        return $this;
    }

    /**
     * Get basket
     *
     * @return \NiftyThrifty\ShopBundle\Entity\Basket 
     */
    public function getBasket()
    {
        return $this->basket;
    }

    /**
     * Set user
     *
     * @param \NiftyThrifty\ShopBundle\Entity\User $user
     * @return Invoice
     */
    public function setUser(\NiftyThrifty\ShopBundle\Entity\User $user = null)
    {
        $this->user = $user;
    
        return $this;
    }

    /**
     * Get user
     *
     * @return \NiftyThrifty\ShopBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @ORM\PrePersist
     */
    public function generateInvoiceNum()
    {
        $nowDate = new \DateTime();
        $dateString = $nowDate->format('Ymd');
        $this->invoiceNum = $dateString . '-' . $this->orderId;
    }
}
