<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
//use NiftyThrifty\ShopBundle\Entity\Basket;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    /**
     * Find if this order has an unpaid basket.  Paid and expired baskets can be
     * safely ignored.
     */
    public function findUnpaidByBasket($basketId)
    {
        $dql = 'SELECT o
                  FROM NiftyThrifty\ShopBundle\Entity\Order o
                 WHERE o.basketId    = :basketId
                   AND o.orderStatus = :statusUnpaid';
        $params = array('basketId'      => $basketId, 
                        'statusUnpaid'  => Order::STATUS_UNPAID);
                        
        try {
            $order = $this->runSingleResultQuery($dql, $params);
        } catch (NoResultException $e) {
            $order = null;
        }
        
        return $order;
    }
}
