<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductTagtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTagtypeRepository extends EntityRepository
{
    /**
     * Find collections for the navigation menu.  Currently all categories ordered
     * by name, but we can consider making this configurable via the database.
     */
    public function findNavigation()
    {
        $dql = "SELECT t
                  FROM NiftyThrifty\ShopBundle\Entity\ProductTagtype t
                 ORDER BY t.productTagtypeName";
        return $this->runQuery($dql);
    }
}
