<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTagRepository extends EntityRepository
{
    /**
     * Find collections for the navigation menu.  Currently all categories ordered
     * by name, but we can consider making this configurable via the database.
     */
    public function findByTagType($productTagtype)
    {
        $dql = "SELECT t
                  FROM NiftyThrifty\ShopBundle\Entity\ProductTag t
                 WHERE t.productTagtypeId = :tagType
                 ORDER BY t.productTagName";
        $params = array(':tagType' => $productTagtype);
        return $this->runQuery($dql, $params);
    }
}
