<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCategorySizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategorySizeRepository extends EntityRepository
{
    /**
     * Find all the sizes in a category, order it by the designated ordering field or,
     * if that's empty, by id.
     */
    public function findByCategoryId($categoryId)
    {
        $dql = "SELECT s
                  FROM NiftyThrifty\ShopBundle\Entity\ProductCategorySize s
                 WHERE s.productCategoryId = :categoryId
                 ORDER BY s.productCategorySizeOrder ASC";
        $params = array(':categoryId' => $categoryId);
        return $this->runQuery($dql, $params);
    }
}
