<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserViewedProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserViewedProductRepository extends EntityRepository
{
    public function findByUserAndProduct($userId, $productId)
    {
        $dql = "SELECT vp
                  FROM  NiftyThrifty\ShopBundle\Entity\UserViewedProduct vp
                 WHERE vp.productId = :productId
                   AND vp.userId = :userId";
        $params = array('userId' => $userId, 'productId' => $productId);
        return $this->runSingleResultQuery($dql, $params);
    }
}
