<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLovedProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLovedProductRepository extends EntityRepository
{
    public function findByUserAndProduct($userId, $productId)
    {
        $dql = 'SELECT ul
                  FROM NiftyThrifty\ShopBundle\Entity\UserLovedProduct ul
                 WHERE ul.productId = :productId
                   AND ul.userId    = :userId';
        $params = array('productId' => $productId, 'userId' => $userId);
        
        return $this->runSingleResultQuery($dql, $params);
    }
}
