<?php

namespace NiftyThrifty\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use NiftyThrifty\ShopBundle\Entity\UserInvitation;

/**
 * UserInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInvitationRepository extends EntityRepository
{
    /**
     * Return a record that is:
     *  1) For the given userId
     *  2) Accepted.
     * This is used to determine if we are to give the inviting user in this record a
     * first purchase credit.
     */
    public function findAcceptedByUserId($userId)
    {
        $dql = "SELECT i
                  FROM NiftyThrifty\ShopBundle\Entity\UserInvitation i
                 WHERE i.userInvitationUserId = :userId
                   AND i.userInvitationStatus = :status";
        $params = array('userId' => $userId,
                        'status' => UserInvitation::STATUS_ACCEPTED);
                        
        try {
            $invitation = $this->runSingleResultQuery($dql, $params);
        } catch (NoResultException $e) {
            $invitation = null;
        }
        
        return $invitation;
    }
}
