NiftyThrifty\ShopBundle\Entity\ProductCategory:
    type: entity
    repositoryClass: ProductCategoryRepository
    table: product_category
    fields:
        productCategoryId:
            id: true
            type: bigint
            nullable: false
            column: product_category_id
            generator:
                strategy: IDENTITY
        productCategoryName:
            type: string
            length: 63
            fixed: false
            nullable: false
            column: product_category_name
        inNavigation:
            type: string
            length: 5
            fixed: false
            nullable: false
            column: in_navigation
        navigationOrder:
            type:   integer
            unsigned: false
            nullable: false
            column: navigation_order
    oneToMany:
        productCategorySizes:
            targetEntity:   ProductCategorySize
            mappedBy:       productCategory
    lifecycleCallbacks: {  }
