NiftyThrifty\ShopBundle\Entity\UserLovedProduct:
    type: entity
    repositoryClass: NiftyThrifty\ShopBundle\Entity\UserLovedProductRepository
    table: user_loved_product
    fields:
        userId:
            id:         true
            type:       integer
            unsigned:   false
            nullable:   false
            column:     user_id
        productId:
            id:         true
            type:       integer
            unsigned:   false
            nullable:   false
            column:     product_id
        loveType:
            type:       string
            length:     10
            nullable:   false
            column:     love_type
        dateLoved:
            type:       datetime
            nullable:   false
            column:     date_loved
        isDeleted:
            type:       integer
            length:     1
            nullable:   false
            column:     is_deleted
            default:    0

    oneToOne:
        product:
            targetEntity: Product
            joinColumn:
                name:                   product_id
                referencedColumnName:   product_id
    manyToOne:
        user:
            targetEntity:   User
            inversedBy:     userLovedProducts
            joinColumn:
                name:                   user_id
                referencedColumnName:   user_id

    lifecycleCallbacks: {  }
