NiftyThrifty\ShopBundle\Entity\UserViewedProduct:
    type: entity
    repositoryClass: NiftyThrifty\ShopBundle\Entity\UserViewedProductRepository
    table: user_viewed_product
    fields:
        userId:
            id:         true
            type:       integer
            unsigned:   false
            nullable:   false
            column:     user_id
        productId:
            id:         true
            type:       integer
            unsigned:   false
            nullable:   false
            column:     product_id
        dateViewed:
            type:       datetime
            nullable:   false
            column:     date_viewed

    oneToOne:
        product:
            targetEntity: Product
            joinColumn:
                name:                   product_id
                referencedColumnName:   product_id
    manyToOne:
        user:
            targetEntity:   User
            inversedBy:     userViewedProducts
            joinColumn:
                name:                   user_id
                referencedColumnName:   user_id

    lifecycleCallbacks: {  }
