CREATE TABLE `order` (
  `order_id`                            bigint(20)                      NOT NULL                    COMMENT 'Id',
  `basket_id`                           bigint(20)                      NOT NULL                    COMMENT 'Basket',
  `order_status`                        enum('paid','unpaid','expired') NOT NULL DEFAULT 'unpaid'   COMMENT 'Status',
  `order_date_creation`                 datetime                        NOT NULL                    COMMENT 'Creation date',
  `order_date_end`                      datetime                        NOT NULL                    COMMENT 'End date',
  `order_user_first_name`               varchar(100)                    NOT NULL                    COMMENT 'User first name',
  `order_user_last_name`                varchar(100)                    NOT NULL                    COMMENT 'User last name',
  `order_user_email`                    varchar(100)                    NOT NULL                    COMMENT 'User email',
  `order_amount`                        float                           NOT NULL DEFAULT '0'        COMMENT 'Amount',
  `order_amount_coupon`                 float                           NOT NULL DEFAULT '0'        COMMENT 'Amount coupon',
  `order_amount_vat`                    float                           NOT NULL DEFAULT '0'        COMMENT 'Amount VAT',
  `order_amount_shipping`               float                           NOT NULL DEFAULT '0'        COMMENT 'Amount shipping',
  `order_amount_credits`                float                           NOT NULL DEFAULT '0'        COMMENT 'Amount credits',
  `order_amount_total`                  float                           NOT NULL DEFAULT '0'        COMMENT 'Amount total',
  `order_products`                      longtext                        NOT NULL                    COMMENT 'Products',
  `order_shipping_method`               enum('classic','express')                DEFAULT 'classic'  COMMENT 'Shipping method',
  `order_shipping_address_first_name`   varchar(64)                     NOT NULL                    COMMENT 'Address shipping first name',
  `order_shipping_address_last_name`    varchar(64)                     NOT NULL                    COMMENT 'Address shipping last name',
  `order_shipping_address_street`       varchar(255)                    NOT NULL                    COMMENT 'Address shipping street',
  `order_shipping_address_city`         varchar(64)                     NOT NULL                    COMMENT 'Address shipping city',
  `order_shipping_address_state`        varchar(64)                     NOT NULL                    COMMENT 'Address shipping state',
  `order_shipping_address_zipcode`      varchar(20)                     NOT NULL                    COMMENT 'Address shipping zipcode',
  `order_shipping_address_country`      varchar(64)                     NOT NULL                    COMMENT 'Address shipping country',
  `order_billing_address_first_name`    varchar(64)                     NOT NULL                    COMMENT 'Address billing first name',
  `order_billing_address_last_name`     varchar(64)                     NOT NULL                    COMMENT 'Address billing last name',
  `order_billing_address_street`        varchar(255)                    NOT NULL                    COMMENT 'Address billing street',
  `order_billing_address_city`          varchar(64)                     NOT NULL                    COMMENT 'Address billing city',
  `order_billing_address_state`         varchar(64)                     NOT NULL                    COMMENT 'Address billing state',
  `order_billing_address_zipcode`       varchar(20)                     NOT NULL                    COMMENT 'Address billing zipcode',
  `order_billing_address_country`       varchar(64)                     NOT NULL                    COMMENT 'Address shipping country',
  `order_user_ip_address`               varchar(255)                    NOT NULL                    COMMENT 'User IP Address',
  `coupon_id`                           bigint(20)                               DEFAULT NULL       COMMENT 'Coupon',
  PRIMARY KEY (`order_id`),
  INDEX (`basket_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Orders' ;