CREATE TABLE `product` (
  `product_id`                              bigint(20)                      NOT NULL,
  `product_name`                            varchar(63)                     NOT NULL,
  `product_description`                     longtext                        NOT NULL,
  `product_category_size_id`                bigint(20)                      NOT NULL,
  `product_look_id`                         int(20)         DEFAULT NULL,
  `product_type_id`                         bigint(20)      DEFAULT NULL,
  `product_overall_condition`               varchar(63)                     NOT NULL,
  `product_price`                           int(11)                         NOT NULL,
  `product_old_price`                       int(11)         DEFAULT NULL,
  `product_discount`                        int(11)         DEFAULT NULL,
  `product_detailed_condition_value`        tinyint(1)                      NOT NULL,
  `product_detailed_condition_description`  varchar(63)                     NOT NULL,
  `product_fabric`                          varchar(255)                    NOT NULL,
  `product_measurements`                    varchar(255)                    NOT NULL,
  `product_availability`                    varchar(255)                    NOT NULL,
  `product_heavy`                           varchar(255)                    NOT NULL,
  `product_visual1`                         varchar(255)    DEFAULT NULL,
  `product_visual1_large`                   varchar(255)    DEFAULT NULL,
  `product_visual2`                         varchar(255)    DEFAULT NULL,
  `product_visual2_large`                   varchar(255)    DEFAULT NULL,
  `product_visual3`                         varchar(255)    DEFAULT NULL,
  `product_visual3_large`                   varchar(255)    DEFAULT NULL,
  `collection_id`                           bigint(20)                      NOT NULL,
  `designer_id`                             bigint(20)      DEFAULT NULL,
  `product_hashtag`                         varchar(255)    DEFAULT NULL,
  `product_instagram_media_id_nifty`        varchar(255)    DEFAULT NULL,
  `product_instagram_media_id_customer`     varchar(255)    DEFAULT NULL,
  `product_taxes`                           double                          NOT NULL,
  `product_taxes_active`                    varchar(255)                    NOT NULL,
  `product_code`                            varchar(10)                     NOT NULL,
  `product_tagsize`                         varchar(255)    DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX (`product_look_id`),
  INDEX (`product_type_id`),
  INDEX (`product_category_size_id`),
  INDEX (`product_price`),
  INDEX (`collection_id`),
  INDEX (`designer_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Products'